// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2dWJZ92IdjSTCw8DZt6Zd6hvADZPwxhs',
    appId: '1:86473586442:web:429abc186e4df4f746acf3',
    messagingSenderId: '86473586442',
    projectId: 'cross-platform-audio',
    authDomain: 'cross-platform-audio.firebaseapp.com',
    storageBucket: 'cross-platform-audio.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuJf-RPN6mSgt5M5jK0ayHm1Kr2Bmg-nc',
    appId: '1:86473586442:android:3dbc4643eabfb15d46acf3',
    messagingSenderId: '86473586442',
    projectId: 'cross-platform-audio',
    storageBucket: 'cross-platform-audio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDd37hIL2cS2jscZAPzvuaSXY7bX0noKo',
    appId: '1:86473586442:ios:485e0788781ed74f46acf3',
    messagingSenderId: '86473586442',
    projectId: 'cross-platform-audio',
    storageBucket: 'cross-platform-audio.appspot.com',
    iosClientId: '86473586442-a7dsuoio45lvgq7ua5s9cfbraonje71d.apps.googleusercontent.com',
    iosBundleId: 'com.example.cpaDemoApp',
  );
}
